### ISSUE TITLE
Typo in the release tag?

### ISSUE THREAD

**Issue by 27182818284590** [prep/beanstalk#27]
Hello! 

Thanks for the new release. I believe there is a typo in the latest tag. All the previous releases did not have `.` (dot) after `v`. The newest release has.

- [v.1.4.6](https://github.com/prep/beanstalk/releases/tag/v.1.4.6)
- [v1.4.5](https://github.com/prep/beanstalk/releases/tag/v1.4.5)
- [v1.4.4](https://github.com/prep/beanstalk/releases/tag/v1.4.4)
- [v1.4.3](https://github.com/prep/beanstalk/releases/tag/v1.4.3)
- [v1.4.2](https://github.com/prep/beanstalk/releases/tag/v1.4.2)

Best from Amsterdam,
27182818284590

**Comment by prep** [comment]
Doh! 🤦 Thanks for noticing, amigo. I just created a `v1.4.7`.
